# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test-vcxagency:
    runs-on: ubuntu-16.04
    needs: [build-image-ubuntu16-vcxagency]
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Docker setup
        run: |
          echo ::set-env name=GITHUB_REPOSITORY_LOWERCASE::$(echo $GITHUB_REPOSITORY | awk '{print tolower($0)}')
          REF_HASH=`echo -n "$GITHUB_REF-$GITHUB_ACTOR" | shasum | cut -f1 -d" "`
          echo ::set-env name=REF_HASH::$(echo $REF_HASH)
          echo ${{ secrets.PACKAGES_ACCESS_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Pull image ubuntu16-vcxagency
        run: |
          set -x
          docker pull docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/ubuntu16-vcxagency:$REF_HASH || true
      - name: Building docker image
        run: |
          set -x
          docker run --rm -i --name libindy-tests \
                              --network host \
                              docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/ubuntu16-vcxagency:$REF_HASH \
                              bash -c '(cd $HOME/indy-sdk/vcx/dummy-cloud-agent && cargo test)'


  test-libvcx:
    runs-on: ubuntu-16.04
    env:
      DOCKER_BUILDKIT: 1
    needs: [build-image-indypool, build-image-ubuntu16-libvcx, build-image-ubuntu16-vcxagency]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Docker setup
        run: |
          echo ::set-env name=GITHUB_REPOSITORY_LOWERCASE::$(echo $GITHUB_REPOSITORY | awk '{print tolower($0)}')
          REF_HASH=`echo -n "$GITHUB_REF-$GITHUB_ACTOR" | shasum | cut -f1 -d" "`
          echo ::set-env name=REF_HASH::$(echo $REF_HASH)
          echo ${{ secrets.PACKAGES_ACCESS_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Pull image ubuntu16-libvcx
        run: |
          set -x
          docker pull docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/ubuntu16-libvcx:$REF_HASH || true
      - name: Pull image indy_pool
        run: |
          set -x
          docker pull docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/indy_pool:$REF_HASH || true
      - name: Run libindy unit tests in Docker
        run: |
          set -x
          docker run -d --name indylocalhost \
                        --network host \
                        docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/indy_pool:$REF_HASH

          docker run -d --name indylocalhost \
                        --network host \
                        docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/vcxagency:$REF_HASH

          docker run --rm -i --name libindy-tests \
                              --network host \
                              docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/ubuntu16-libvcx:$REF_HASH \
                              bash -c '(cd $HOME/indy-sdk/vcx/libvcx && cargo test --release)'

